### ISSUE TITLE
Transfer over burntfen.net content here.

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/richardlitt.github.com#42]

**Comment by RichardLitt** [comment]
Also, remove the old website from the internet.

**Comment by RichardLitt** [comment]
I am afraid I have broken https://www.burntfen.com/comic/dean/xkde in my shit over to https. Would you like to fix it, @deanoemcke? https://github.com/RichardLitt/richardlitt.github.com/tree/master/comic/dean

**Comment by deaconmeek** [comment]
wat? no-one uses php anymore?
i've ported it to pure js, and given it a new home: https://deaconmeek.github.io/
that's for the hosting bro!

**Comment by deaconmeek** [comment]
Feel free to delete from your repo.

**Comment by RichardLitt** [comment]
I thought you were a spammer there.

**Comment by deaconmeek** [comment]
oh yeah. posting from my alterego. how's malta? :D

**Comment by RichardLitt** [comment]
Antigua? It's pretty sweet. Had a lot of fun here. Back on Tuesday.

**Comment by deaconmeek** [comment]
nice! you're the only person i know that is responsive enough to github issues that you can use it as a chat.

**Comment by RichardLitt** [comment]
Silence proves the point. Was busy working on another site. 

Well, no one else watches this repo, so why not.
