### ISSUE TITLE
Review: Add "Red Winter" by Anneli Furmark

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/richardlitt.github.com#79]
@VernL, can you add this and see how the process is? 

---

I bought this as part of the [Drawn and Quarterly](https://www.drawnandquarterly.com/) monthly graphic novel club here in Montréal (just as I have bought [_The Unwritten_](https://www.burntfen.com/the-litt-review/the-unwritten---tommy-taylor-and-the-ship-that-sank-twice/) and a few other books which I haven't reviewed here yet). The bookclub gives me the option of learning more about the art of graphic novels, and getting out of my comfort zone. I wouldn't have read this book, otherwise.

I am glad I did. This book covers an affair between Siv, a married mother of three, and a young communist, Ulrik, in a town in northern Sweden in the 70s.
The book is set into chapters named after the various characters: Liv, Ulrik, Börje (Liv's husband), Marita and Peter, her children. Through a series of vignettes, a narrative forms - from initial hugs in the snow, to dangerous midnight trysts, to the inevitable conversations between Liv and Börje. We see the children's world, too, which focuses more on how the children aren't getting direction from their parents, and as they wander through adolescence.

The book, in a word, is depressing. Unlike normal literature, a graphic novel has multiple different ways of conveying a sense of place: perspective, detail, description, voice overs, and - especially here - colour. The entire book is painted in watercolour with almost two brushes alone, in swaths of blue, gold, and, of course, red. The blue and gold are omnipresent in the scenery, while the red is mostly limited to items of clothing, some books. The two colours give the winter a wonderful sense of alienation and coldness. No light is quite bright enough to keep the blue out of the corners of the room. The characters are drawn as sketches, almost sloppily, and most faces in the cold tend to have swirls where flushed cheeks would be. Even without this effect, you feel the winter bearing down, and the night always seems to be closing in. This pairs beautifully with the two lovers, unable to see how their actions are hurting those around them, and how their own affair lacks substance in itself. Neither is willing to quite leave for the other, and neither considers what will happen in the end.

Some of the scenes are heartrending. We have another example of a child walking on the road in the winter in Sweden - the comparison to Knausgaard's _My Struggle_, for me, is inescapable (already, I've mentioned and then deleted it in this review several times). And the first chapter from Börje's perspective, where he ends sitting in front of the TV after his wife leaves to go who-knows-where - what can be more pathetic than a man not knowing why his wife is falling out of love? The sense of solitude is crushing.

I didn't follow all of the politics in the book. I don't have a history of dealing with splintered democratic and communist groups, and some of the conversations between comrades struck me as outmoded and bizarre, like I was reading an anarchist dystopic fiction. There's also a fair amount of journal snooping, something I would consider profane in my own life; it was hard to see it happen several times. Does everyone go around reading other people's journals? It seems a trope.

All told, this was a beautiful little graphic novel.

**Comment by VernL** [comment]
@RichardLitt I can't seem to find the process file. I could very well be blind or perhaps it's not in the repo.

**Comment by RichardLitt** [comment]
It's here! https://github.com/RichardLitt/knowledge/blob/master/processes/publishing-book-review.md

**Comment by VernL** [comment]
The process is well documented. Three steps took a long time and could be improved:
  - Hunting for a cover image. (thinking about copyrights, quality etc.) 
  - Adding the image to the site. (Add running gulp to the process. Also, the gulp task should ignore unchanged images...)
  - Mailchimp campaign (I always waste time in Mailchimp. An automated campaign linked to a RSS feed would clean this up.)

**Comment by RichardLitt** [comment]
That sounds right to me. 

Can you work on the Mailchimp campaign? I think adding RSS would work well. The best solution for this is probably to move The Litt Review to it's own site entirely.
